#
# Copyright (c) 2022 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#

cmake_minimum_required(VERSION 3.20.0)

# Flag which defines whether application is compiled as gateway/dongle or headset
add_compile_definitions(HEADSET=1)
add_compile_definitions(GATEWAY=2)

find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})

project(new-tiresias)

string(TIMESTAMP NRF5340_AUDIO_CORE_APP_COMP_DATE "%a %b %d %H:%M:%S %Y")

# Generate fw_info_app.c
configure_file("${CMAKE_CURRENT_SOURCE_DIR}/src/utils/fw_info_app.c.in"
               "${CMAKE_BINARY_DIR}/fw_info_app.c"
               @ONLY)

target_sources(app PRIVATE
    ${CMAKE_BINARY_DIR}/fw_info_app.c
    )

target_sources(app PRIVATE src/main.c)

# Include application events and configuration headers
zephyr_library_include_directories(
    include
    src/audio
    src/application
    src/bluetooth
    src/codec
    src/drivers
    src/modules
    src/utils
    src/utils/macros
    src/SigmaStudioFiles
)

# Application sources
add_subdirectory(src/audio)
add_subdirectory(src/application)
add_subdirectory(src/bluetooth)
add_subdirectory(src/codec)
add_subdirectory(src/drivers)
add_subdirectory(src/modules)
add_subdirectory(src/utils)
add_subdirectory(src/SigmaStudioFiles)
