/*
 * Copyright (c) 2026 Tiresias Firmware Team
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
 */

#include "codec_program.h"

#include "codec_contract.h"
#include "sigma_exports.h"

#include <errno.h>
#include <zephyr/sys/util.h>

static const sub_addr_t parameter_addresses[CODEC_PARAMETER_COUNT] = {
  [CODEC_PARAMETER_INDEX(DSP_PARAMETER_ID_ADC_SELECT)] = (sub_addr_t)MOD_ADCSELECT_MONOSWSLEW_ADDR,
  [CODEC_PARAMETER_INDEX(DSP_PARAMETER_ID_SOURCE_SELECT)] = (sub_addr_t)MOD_SOURCESELECT_STEREOSWSLEW_ADDR,
  [CODEC_PARAMETER_INDEX(DSP_PARAMETER_ID_BAND_1_COMPRESSOR_LUT)]
  = (sub_addr_t)MOD_COMPRESSOR_BANK_BAND1COMPRESSOR_ALG0_MONONOPOSTGAINSUB1TAB0_ADDR,
  [CODEC_PARAMETER_INDEX(DSP_PARAMETER_ID_BAND_2_COMPRESSOR_LUT)]
  = (sub_addr_t)MOD_COMPRESSOR_BANK_BAND2COMPRESSOR_ALG0_MONONOPOSTGAINSUB2TAB0_ADDR,
  [CODEC_PARAMETER_INDEX(DSP_PARAMETER_ID_BAND_3_COMPRESSOR_LUT)]
  = (sub_addr_t)MOD_COMPRESSOR_BANK_BAND3COMPRESSOR_ALG0_MONONOPOSTGAINSUB3TAB0_ADDR,
  [CODEC_PARAMETER_INDEX(DSP_PARAMETER_ID_BAND_4_COMPRESSOR_LUT)]
  = (sub_addr_t)MOD_COMPRESSOR_BANK_BAND4COMPRESSOR_ALG0_MONONOPOSTGAINSUB4TAB0_ADDR,
  [CODEC_PARAMETER_INDEX(DSP_PARAMETER_ID_BAND_5_COMPRESSOR_LUT)]
  = (sub_addr_t)MOD_COMPRESSOR_BANK_BAND5COMPRESSOR_ALG0_MONONOPOSTGAINSUB5TAB0_ADDR,
  [CODEC_PARAMETER_INDEX(DSP_PARAMETER_ID_BAND_6_COMPRESSOR_LUT)]
  = (sub_addr_t)MOD_COMPRESSOR_BANK_BAND6COMPRESSOR_ALG0_MONONOPOSTGAINSUB6TAB0_ADDR,
  [CODEC_PARAMETER_INDEX(DSP_PARAMETER_ID_BAND_7_COMPRESSOR_LUT)]
  = (sub_addr_t)MOD_COMPRESSOR_BANK_BAND7COMPRESSOR_ALG0_MONONOPOSTGAINSUB7TAB0_ADDR,
  [CODEC_PARAMETER_INDEX(DSP_PARAMETER_ID_BAND_8_COMPRESSOR_LUT)]
  = (sub_addr_t)MOD_COMPRESSOR_BANK_BAND8COMPRESSOR_ALG0_MONONOPOSTGAINSUB8TAB0_ADDR,
  [CODEC_PARAMETER_INDEX(DSP_PARAMETER_ID_PHASE_COMP_GAIN_1)] = (sub_addr_t)MOD_PHASE_COMP_GAIN1_GAIN1940ALGNS1_ADDR,
  [CODEC_PARAMETER_INDEX(DSP_PARAMETER_ID_PHASE_COMP_GAIN_2)] = (sub_addr_t)MOD_PHASE_COMP_GAIN2_GAIN1940ALGNS2_ADDR,
  [CODEC_PARAMETER_INDEX(DSP_PARAMETER_ID_PHASE_COMP_GAIN_3)] = (sub_addr_t)MOD_PHASE_COMP_GAIN3_GAIN1940ALGNS3_ADDR,
  [CODEC_PARAMETER_INDEX(DSP_PARAMETER_ID_OUTPUT_HEADROOM_GAIN)] = (sub_addr_t)MOD_OUTPUTHEADROOM_GAIN1940ALGNS4_ADDR,
  [CODEC_PARAMETER_INDEX(DSP_PARAMETER_ID_SOFT_CLIP_LUT)] = (sub_addr_t)MOD_SOFTCLIP_ALG0_GAINTABLE0_ADDR,
};

int get_param_address(uint8_t id, sub_addr_t* address)
{
  const struct codec_parameter* parameter;

  if (address == NULL) {
    return -EINVAL;
  }

  parameter = codec_contract_find(id);
  if (parameter == NULL) {
    return -ENOENT;
  }

  *address = parameter_addresses[CODEC_PARAMETER_INDEX(parameter->id)];
  return 0;
}

BUILD_ASSERT(
    ARRAY_SIZE(parameter_addresses) == CODEC_PARAMETER_COUNT, "Every contract parameter needs a SigmaStudio address");
