/*
 * Copyright (c) 2026 Tiresias Firmware Team
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
 */

#include "codec_contract.h"

#include <zephyr/sys/util.h>

const struct codec_parameter codec_contract[CODEC_PARAMETER_COUNT] = {
  { DSP_PARAMETER_ID_ADC_SELECT, DSP_BLOCK_ID_ADC_SELECT, CODEC_BYTES_FROM_WORDS(1), CODEC_CONTRACT_FLAG_WRITABLE },
  { DSP_PARAMETER_ID_SOURCE_SELECT, DSP_BLOCK_ID_SOURCE_SELECT, CODEC_BYTES_FROM_WORDS(1),
      CODEC_CONTRACT_FLAG_WRITABLE },
  { DSP_PARAMETER_ID_BAND_1_COMPRESSOR_LUT, DSP_BLOCK_ID_BAND_1_COMPRESSOR, CODEC_BYTES_FROM_WORDS(34),
      CODEC_CONTRACT_FLAG_WRITABLE },
  { DSP_PARAMETER_ID_BAND_2_COMPRESSOR_LUT, DSP_BLOCK_ID_BAND_2_COMPRESSOR, CODEC_BYTES_FROM_WORDS(34),
      CODEC_CONTRACT_FLAG_WRITABLE },
  { DSP_PARAMETER_ID_BAND_3_COMPRESSOR_LUT, DSP_BLOCK_ID_BAND_3_COMPRESSOR, CODEC_BYTES_FROM_WORDS(34),
      CODEC_CONTRACT_FLAG_WRITABLE },
  { DSP_PARAMETER_ID_BAND_4_COMPRESSOR_LUT, DSP_BLOCK_ID_BAND_4_COMPRESSOR, CODEC_BYTES_FROM_WORDS(34),
      CODEC_CONTRACT_FLAG_WRITABLE },
  { DSP_PARAMETER_ID_BAND_5_COMPRESSOR_LUT, DSP_BLOCK_ID_BAND_5_COMPRESSOR, CODEC_BYTES_FROM_WORDS(34),
      CODEC_CONTRACT_FLAG_WRITABLE },
  { DSP_PARAMETER_ID_BAND_6_COMPRESSOR_LUT, DSP_BLOCK_ID_BAND_6_COMPRESSOR, CODEC_BYTES_FROM_WORDS(34),
      CODEC_CONTRACT_FLAG_WRITABLE },
  { DSP_PARAMETER_ID_BAND_7_COMPRESSOR_LUT, DSP_BLOCK_ID_BAND_7_COMPRESSOR, CODEC_BYTES_FROM_WORDS(34),
      CODEC_CONTRACT_FLAG_WRITABLE },
  { DSP_PARAMETER_ID_BAND_8_COMPRESSOR_LUT, DSP_BLOCK_ID_BAND_8_COMPRESSOR, CODEC_BYTES_FROM_WORDS(34),
      CODEC_CONTRACT_FLAG_WRITABLE },
  { DSP_PARAMETER_ID_PHASE_COMP_GAIN_1, DSP_BLOCK_ID_PHASE_COMP_GAIN_1, CODEC_BYTES_FROM_WORDS(1),
      CODEC_CONTRACT_FLAG_WRITABLE },
  { DSP_PARAMETER_ID_PHASE_COMP_GAIN_2, DSP_BLOCK_ID_PHASE_COMP_GAIN_2, CODEC_BYTES_FROM_WORDS(1),
      CODEC_CONTRACT_FLAG_WRITABLE },
  { DSP_PARAMETER_ID_PHASE_COMP_GAIN_3, DSP_BLOCK_ID_PHASE_COMP_GAIN_3, CODEC_BYTES_FROM_WORDS(1),
      CODEC_CONTRACT_FLAG_WRITABLE },
  { DSP_PARAMETER_ID_OUTPUT_HEADROOM_GAIN, DSP_BLOCK_ID_OUTPUT_HEADROOM, CODEC_BYTES_FROM_WORDS(1),
      CODEC_CONTRACT_FLAG_WRITABLE },
  { DSP_PARAMETER_ID_SOFT_CLIP_LUT, DSP_BLOCK_ID_SOFT_CLIP, CODEC_BYTES_FROM_WORDS(45), 0 },
};

const struct codec_parameter* codec_contract_find(uint8_t id)
{
  const struct codec_parameter* parameter;

  if (id == 0U || id > CODEC_PARAMETER_COUNT) {
    return NULL;
  }

  parameter = &codec_contract[CODEC_PARAMETER_INDEX(id)];
  if (parameter->id != id) {
    return NULL;
  }

  return parameter;
}

BUILD_ASSERT(sizeof(struct codec_parameter) == 4U, "The fixed contract fingerprint requires four-byte entries");
BUILD_ASSERT(DSP_PARAMETER_ID_SOFT_CLIP_LUT == CODEC_PARAMETER_COUNT, "Parameter IDs must remain dense");
