/*
 * Copyright (c) 2026 Tiresias Firmware Team
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
 */

#include "dsp_parameter_catalog.h"

#include <zephyr/sys/util.h>

const struct dsp_parameter dsp_parameter_contract[DSP_PARAMETER_COUNT] = {
  { DSP_PARAMETER_ID_ADC_SELECT, DSP_BLOCK_ID_ADC_SELECT, BYTES_FROM_WORDS(1), DSP_PARAMETER_CONTRACT_FLAG_WRITABLE },
  { DSP_PARAMETER_ID_SOURCE_SELECT, DSP_BLOCK_ID_SOURCE_SELECT, BYTES_FROM_WORDS(1), DSP_PARAMETER_CONTRACT_FLAG_WRITABLE },
  { DSP_PARAMETER_ID_BAND_1_COMPRESSOR_LUT, DSP_BLOCK_ID_BAND_1_COMPRESSOR, BYTES_FROM_WORDS(34), 0 },
  { DSP_PARAMETER_ID_BAND_2_COMPRESSOR_LUT, DSP_BLOCK_ID_BAND_2_COMPRESSOR, BYTES_FROM_WORDS(34), 0 },
  { DSP_PARAMETER_ID_BAND_3_COMPRESSOR_LUT, DSP_BLOCK_ID_BAND_3_COMPRESSOR, BYTES_FROM_WORDS(34), 0 },
  { DSP_PARAMETER_ID_BAND_4_COMPRESSOR_LUT, DSP_BLOCK_ID_BAND_4_COMPRESSOR, BYTES_FROM_WORDS(34), 0 },
  { DSP_PARAMETER_ID_BAND_5_COMPRESSOR_LUT, DSP_BLOCK_ID_BAND_5_COMPRESSOR, BYTES_FROM_WORDS(34), 0 },
  { DSP_PARAMETER_ID_BAND_6_COMPRESSOR_LUT, DSP_BLOCK_ID_BAND_6_COMPRESSOR, BYTES_FROM_WORDS(34), 0 },
  { DSP_PARAMETER_ID_BAND_7_COMPRESSOR_LUT, DSP_BLOCK_ID_BAND_7_COMPRESSOR, BYTES_FROM_WORDS(34), 0 },
  { DSP_PARAMETER_ID_BAND_8_COMPRESSOR_LUT, DSP_BLOCK_ID_BAND_8_COMPRESSOR, BYTES_FROM_WORDS(34), 0 },
  { DSP_PARAMETER_ID_PHASE_COMP_GAIN_1, DSP_BLOCK_ID_PHASE_COMP_GAIN_1, BYTES_FROM_WORDS(1), DSP_PARAMETER_CONTRACT_FLAG_WRITABLE },
  { DSP_PARAMETER_ID_PHASE_COMP_GAIN_2, DSP_BLOCK_ID_PHASE_COMP_GAIN_2, BYTES_FROM_WORDS(1), DSP_PARAMETER_CONTRACT_FLAG_WRITABLE },
  { DSP_PARAMETER_ID_PHASE_COMP_GAIN_3, DSP_BLOCK_ID_PHASE_COMP_GAIN_3, BYTES_FROM_WORDS(1), DSP_PARAMETER_CONTRACT_FLAG_WRITABLE },
  { DSP_PARAMETER_ID_OUTPUT_HEADROOM_GAIN, DSP_BLOCK_ID_OUTPUT_HEADROOM, BYTES_FROM_WORDS(1), DSP_PARAMETER_CONTRACT_FLAG_WRITABLE },
  { DSP_PARAMETER_ID_SOFT_CLIP_LUT, DSP_BLOCK_ID_SOFT_CLIP, BYTES_FROM_WORDS(45), 0 },
};

const struct dsp_parameter* dsp_parameter_definition(uint8_t id)
{
  const struct dsp_parameter* parameter;

  if (id == 0U || id > DSP_PARAMETER_COUNT) {
    return NULL;
  }

  parameter = &dsp_parameter_contract[id - 1U];
  return parameter->id == id ? parameter : NULL;
}

BUILD_ASSERT(sizeof(struct dsp_parameter) == 4U, "The fixed contract fingerprint requires four-byte entries");
BUILD_ASSERT(DSP_PARAMETER_ID_SOFT_CLIP_LUT == DSP_PARAMETER_COUNT, "Parameter IDs must remain dense");
