/*
 * Copyright (c) 2026 Tiresias Firmware Team
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
 */

#include "dsp_parameter_catalog.h"

#include "adau_1787_IC_1_SIGMA_PARAM.h"
#if defined(CONFIG_AUDIO_CODEC_ADAU1787)
#include "adau1787.h"
#endif

#include <zephyr/sys/util.h>

#if defined(CONFIG_AUDIO_CODEC_ADAU1787)
/* Defined by the generated SigmaStudio image included by adau1787.c. */
extern uint8_t Param_Data_IC_1_Sigma[];
#endif

const struct dsp_parameter dsp_parameter_contract[DSP_PARAMETER_COUNT] = {
  { DSP_PARAMETER_ID_ADC_SELECT, DSP_BLOCK_ID_ADC_SELECT, 4, DSP_PARAMETER_CONTRACT_FLAG_WRITABLE },
  { DSP_PARAMETER_ID_SOURCE_SELECT, DSP_BLOCK_ID_SOURCE_SELECT, 4, DSP_PARAMETER_CONTRACT_FLAG_WRITABLE },
  { DSP_PARAMETER_ID_BAND_1_COMPRESSOR_LUT, DSP_BLOCK_ID_BAND_1_COMPRESSOR, 136, 0 },
  { DSP_PARAMETER_ID_BAND_2_COMPRESSOR_LUT, DSP_BLOCK_ID_BAND_2_COMPRESSOR, 136, 0 },
  { DSP_PARAMETER_ID_BAND_3_COMPRESSOR_LUT, DSP_BLOCK_ID_BAND_3_COMPRESSOR, 136, 0 },
  { DSP_PARAMETER_ID_BAND_4_COMPRESSOR_LUT, DSP_BLOCK_ID_BAND_4_COMPRESSOR, 136, 0 },
  { DSP_PARAMETER_ID_BAND_5_COMPRESSOR_LUT, DSP_BLOCK_ID_BAND_5_COMPRESSOR, 136, 0 },
  { DSP_PARAMETER_ID_BAND_6_COMPRESSOR_LUT, DSP_BLOCK_ID_BAND_6_COMPRESSOR, 136, 0 },
  { DSP_PARAMETER_ID_BAND_7_COMPRESSOR_LUT, DSP_BLOCK_ID_BAND_7_COMPRESSOR, 136, 0 },
  { DSP_PARAMETER_ID_BAND_8_COMPRESSOR_LUT, DSP_BLOCK_ID_BAND_8_COMPRESSOR, 136, 0 },
  { DSP_PARAMETER_ID_PHASE_COMP_GAIN_1, DSP_BLOCK_ID_PHASE_COMP_GAIN_1, 4, DSP_PARAMETER_CONTRACT_FLAG_WRITABLE },
  { DSP_PARAMETER_ID_PHASE_COMP_GAIN_2, DSP_BLOCK_ID_PHASE_COMP_GAIN_2, 4, DSP_PARAMETER_CONTRACT_FLAG_WRITABLE },
  { DSP_PARAMETER_ID_PHASE_COMP_GAIN_3, DSP_BLOCK_ID_PHASE_COMP_GAIN_3, 4, DSP_PARAMETER_CONTRACT_FLAG_WRITABLE },
  { DSP_PARAMETER_ID_OUTPUT_HEADROOM_GAIN, DSP_BLOCK_ID_OUTPUT_HEADROOM, 4, DSP_PARAMETER_CONTRACT_FLAG_WRITABLE },
  { DSP_PARAMETER_ID_SOFT_CLIP_LUT, DSP_BLOCK_ID_SOFT_CLIP, 180, 0 },
};

const struct dsp_parameter* dsp_parameter_definition(uint8_t id)
{
  const struct dsp_parameter* parameter;

  if (id == 0U || id > DSP_PARAMETER_COUNT) {
    return NULL;
  }

  parameter = &dsp_parameter_contract[id - 1U];
  return parameter->id == id ? parameter : NULL;
}

const uint16_t dsp_parameter_addresses[DSP_PARAMETER_COUNT + 1U] = {
  [DSP_PARAMETER_ID_ADC_SELECT] = MOD_ADCSELECT_MONOSWSLEW_ADDR,
  [DSP_PARAMETER_ID_SOURCE_SELECT] = MOD_SOURCESELECT_STEREOSWSLEW_ADDR,
  [DSP_PARAMETER_ID_BAND_1_COMPRESSOR_LUT] = MOD_COMPRESSOR_BANK_BAND1COMPRESSOR_ALG0_MONONOPOSTGAINSUB1TAB0_ADDR,
  [DSP_PARAMETER_ID_BAND_2_COMPRESSOR_LUT] = MOD_COMPRESSOR_BANK_BAND2COMPRESSOR_ALG0_MONONOPOSTGAINSUB2TAB0_ADDR,
  [DSP_PARAMETER_ID_BAND_3_COMPRESSOR_LUT] = MOD_COMPRESSOR_BANK_BAND3COMPRESSOR_ALG0_MONONOPOSTGAINSUB3TAB0_ADDR,
  [DSP_PARAMETER_ID_BAND_4_COMPRESSOR_LUT] = MOD_COMPRESSOR_BANK_BAND4COMPRESSOR_ALG0_MONONOPOSTGAINSUB4TAB0_ADDR,
  [DSP_PARAMETER_ID_BAND_5_COMPRESSOR_LUT] = MOD_COMPRESSOR_BANK_BAND5COMPRESSOR_ALG0_MONONOPOSTGAINSUB5TAB0_ADDR,
  [DSP_PARAMETER_ID_BAND_6_COMPRESSOR_LUT] = MOD_COMPRESSOR_BANK_BAND6COMPRESSOR_ALG0_MONONOPOSTGAINSUB6TAB0_ADDR,
  [DSP_PARAMETER_ID_BAND_7_COMPRESSOR_LUT] = MOD_COMPRESSOR_BANK_BAND7COMPRESSOR_ALG0_MONONOPOSTGAINSUB7TAB0_ADDR,
  [DSP_PARAMETER_ID_BAND_8_COMPRESSOR_LUT] = MOD_COMPRESSOR_BANK_BAND8COMPRESSOR_ALG0_MONONOPOSTGAINSUB8TAB0_ADDR,
  [DSP_PARAMETER_ID_PHASE_COMP_GAIN_1] = MOD_PHASE_COMP_GAIN1_GAIN1940ALGNS1_ADDR,
  [DSP_PARAMETER_ID_PHASE_COMP_GAIN_2] = MOD_PHASE_COMP_GAIN2_GAIN1940ALGNS2_ADDR,
  [DSP_PARAMETER_ID_PHASE_COMP_GAIN_3] = MOD_PHASE_COMP_GAIN3_GAIN1940ALGNS3_ADDR,
  [DSP_PARAMETER_ID_OUTPUT_HEADROOM_GAIN] = MOD_OUTPUTHEADROOM_GAIN1940ALGNS4_ADDR,
  [DSP_PARAMETER_ID_SOFT_CLIP_LUT] = MOD_SOFTCLIP_ALG0_GAINTABLE0_ADDR,
};

const uint8_t* dsp_parameter_default(uint8_t id)
{
#if defined(CONFIG_AUDIO_CODEC_ADAU1787)
  if (dsp_parameter_definition(id) == NULL) {
    return NULL;
  }

  return &Param_Data_IC_1_Sigma[dsp_parameter_addresses[id] - ADAU1787_PARAM_RAM_BASE];
#else
  ARG_UNUSED(id);

  return NULL;
#endif
}

BUILD_ASSERT(sizeof(struct dsp_parameter) == 4U, "The fixed contract fingerprint requires four-byte entries");
BUILD_ASSERT(DSP_PARAMETER_ID_SOFT_CLIP_LUT == DSP_PARAMETER_COUNT, "Parameter IDs must remain dense");
BUILD_ASSERT(DSP_PARAMETER_MAX_BYTE_COUNT <= UINT8_MAX, "Parameter byte counts must fit in the public contract");
BUILD_ASSERT(MOD_COMPRESSOR_BANK_BAND1COMPRESSOR_ALG0_DATA_ADR_ADDR
            == MOD_COMPRESSOR_BANK_BAND1COMPRESSOR_ALG0_MONONOPOSTGAINSUB1TAB0_ADDR + 136U
        && MOD_COMPRESSOR_BANK_BAND2COMPRESSOR_ALG0_DATA_ADR_ADDR
            == MOD_COMPRESSOR_BANK_BAND2COMPRESSOR_ALG0_MONONOPOSTGAINSUB2TAB0_ADDR + 136U
        && MOD_COMPRESSOR_BANK_BAND3COMPRESSOR_ALG0_DATA_ADR_ADDR
            == MOD_COMPRESSOR_BANK_BAND3COMPRESSOR_ALG0_MONONOPOSTGAINSUB3TAB0_ADDR + 136U
        && MOD_COMPRESSOR_BANK_BAND4COMPRESSOR_ALG0_DATA_ADR_ADDR
            == MOD_COMPRESSOR_BANK_BAND4COMPRESSOR_ALG0_MONONOPOSTGAINSUB4TAB0_ADDR + 136U
        && MOD_COMPRESSOR_BANK_BAND5COMPRESSOR_ALG0_DATA_ADR_ADDR
            == MOD_COMPRESSOR_BANK_BAND5COMPRESSOR_ALG0_MONONOPOSTGAINSUB5TAB0_ADDR + 136U
        && MOD_COMPRESSOR_BANK_BAND6COMPRESSOR_ALG0_DATA_ADR_ADDR
            == MOD_COMPRESSOR_BANK_BAND6COMPRESSOR_ALG0_MONONOPOSTGAINSUB6TAB0_ADDR + 136U
        && MOD_COMPRESSOR_BANK_BAND7COMPRESSOR_ALG0_DATA_ADR_ADDR
            == MOD_COMPRESSOR_BANK_BAND7COMPRESSOR_ALG0_MONONOPOSTGAINSUB7TAB0_ADDR + 136U
        && MOD_COMPRESSOR_BANK_BAND8COMPRESSOR_ALG0_DATA_ADR_ADDR
            == MOD_COMPRESSOR_BANK_BAND8COMPRESSOR_ALG0_MONONOPOSTGAINSUB8TAB0_ADDR + 136U,
    "Compressor LUT bindings must cover exactly 136 DSP bytes");
BUILD_ASSERT(MOD_SOFTCLIP_ALG0_HOLD_ADDR == MOD_SOFTCLIP_ALG0_GAINTABLE0_ADDR + 180U,
    "Soft Clip LUT binding must cover exactly 180 DSP bytes");
