/*
 * Copyright (c) 2026 Tiresias Firmware Team
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
 */

#include "param_defaults.h"

#include "adau1787.h"
#include "adau_1787_IC_1_SIGMA_PARAM.h"

#include <zephyr/sys/util.h>

/* Defined by the generated SigmaStudio image included by adau1787.c. */
extern uint8_t Param_Data_IC_1_Sigma[];

#define PARAM_DEFAULT(address) (&Param_Data_IC_1_Sigma[(address) - ADAU1787_PARAM_RAM_BASE])

const uint8_t* const dsp_parameter_defaults[DSP_PARAMETER_COUNT + 1U] = {
  [DSP_PARAMETER_ID_ADC_SELECT] = PARAM_DEFAULT(MOD_ADCSELECT_MONOSWSLEW_ADDR),
  [DSP_PARAMETER_ID_SOURCE_SELECT] = PARAM_DEFAULT(MOD_SOURCESELECT_STEREOSWSLEW_ADDR),
  [DSP_PARAMETER_ID_BAND_1_COMPRESSOR_LUT] = PARAM_DEFAULT(MOD_COMPRESSOR_BANK_BAND1COMPRESSOR_ALG0_MONONOPOSTGAINSUB1TAB0_ADDR),
  [DSP_PARAMETER_ID_BAND_2_COMPRESSOR_LUT] = PARAM_DEFAULT(MOD_COMPRESSOR_BANK_BAND2COMPRESSOR_ALG0_MONONOPOSTGAINSUB2TAB0_ADDR),
  [DSP_PARAMETER_ID_BAND_3_COMPRESSOR_LUT] = PARAM_DEFAULT(MOD_COMPRESSOR_BANK_BAND3COMPRESSOR_ALG0_MONONOPOSTGAINSUB3TAB0_ADDR),
  [DSP_PARAMETER_ID_BAND_4_COMPRESSOR_LUT] = PARAM_DEFAULT(MOD_COMPRESSOR_BANK_BAND4COMPRESSOR_ALG0_MONONOPOSTGAINSUB4TAB0_ADDR),
  [DSP_PARAMETER_ID_BAND_5_COMPRESSOR_LUT] = PARAM_DEFAULT(MOD_COMPRESSOR_BANK_BAND5COMPRESSOR_ALG0_MONONOPOSTGAINSUB5TAB0_ADDR),
  [DSP_PARAMETER_ID_BAND_6_COMPRESSOR_LUT] = PARAM_DEFAULT(MOD_COMPRESSOR_BANK_BAND6COMPRESSOR_ALG0_MONONOPOSTGAINSUB6TAB0_ADDR),
  [DSP_PARAMETER_ID_BAND_7_COMPRESSOR_LUT] = PARAM_DEFAULT(MOD_COMPRESSOR_BANK_BAND7COMPRESSOR_ALG0_MONONOPOSTGAINSUB7TAB0_ADDR),
  [DSP_PARAMETER_ID_BAND_8_COMPRESSOR_LUT] = PARAM_DEFAULT(MOD_COMPRESSOR_BANK_BAND8COMPRESSOR_ALG0_MONONOPOSTGAINSUB8TAB0_ADDR),
  [DSP_PARAMETER_ID_PHASE_COMP_GAIN_1] = PARAM_DEFAULT(MOD_PHASE_COMP_GAIN1_GAIN1940ALGNS1_ADDR),
  [DSP_PARAMETER_ID_PHASE_COMP_GAIN_2] = PARAM_DEFAULT(MOD_PHASE_COMP_GAIN2_GAIN1940ALGNS2_ADDR),
  [DSP_PARAMETER_ID_PHASE_COMP_GAIN_3] = PARAM_DEFAULT(MOD_PHASE_COMP_GAIN3_GAIN1940ALGNS3_ADDR),
  [DSP_PARAMETER_ID_OUTPUT_HEADROOM_GAIN] = PARAM_DEFAULT(MOD_OUTPUTHEADROOM_GAIN1940ALGNS4_ADDR),
  [DSP_PARAMETER_ID_SOFT_CLIP_LUT] = PARAM_DEFAULT(MOD_SOFTCLIP_ALG0_GAINTABLE0_ADDR),
};

BUILD_ASSERT(ARRAY_SIZE(dsp_parameter_defaults) == DSP_PARAMETER_COUNT + 1U,
    "Parameter defaults must be indexed by every parameter ID");

#undef PARAM_DEFAULT
