SOURCE_DIR="/Users/felipepimenta/Library/Containers/com.isaacmarovitz.Whisky/Bottles/54411E0A-1D86-4A0D-91D6-7D2150108E40/drive_c/users/crossover/Desktop/exports"
DESTINATION_DIR="/Users/felipepimenta/Developer/tiresias-firmware/src/SigmaStudioFiles"
